{{- if and .Values.little_sample_cluster.podMonitor.enabled .Values.little_sample_cluster.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "little-sample-cluster.fullname" . }}
  labels:
    {{- include "little-sample-cluster.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "little-sample-cluster.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      {{- with .Values.little_sample_cluster.podMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.little_sample_cluster.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
{{- end }}
