{{- range $registry, $creds := .Values.registryCredentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred-{{ $registry | replace "." "-" | replace "/" "-" }}
  labels:
    {{- include "little-sample-cluster.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ dict "auths" (dict $registry (dict "username" $creds.username "password" $creds.password "auth" (printf "%s:%s" $creds.username $creds.password | b64enc))) | toJson | b64enc }}
{{- end }}
